import "./globals.css";

export const metadata = {
  title: "Andrei Popov Portfolio",
  description: "Generated by create next app", //TODO: change description and favicon
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
